version: '3.4'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      network: host
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: home_automation_local_django
    container_name: django_haut
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: home_automation_production_postgres
    container_name: postgres_haut
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: home_automation_local_docs
#    container_name: docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./home_automation:/app/home_automation:z
#    ports:
#      - "7000:7000"
#    command: /start-docs

  redis:
    image: redis:6
    container_name: redis_haut

  celeryworker:
    <<: *django
    image: home_automation_local_celeryworker
    container_name: celeryworker_haut
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: home_automation_local_celerybeat
    container_name: celerybeat_haut
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: home_automation_local_flower
    container_name: flower_haut
    ports:
      - "5555:5555"
    command: /start-flower
