version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: home_automation_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: home_automation_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres


  redis:
    image: redis:7
    container_name: redis

  celeryworker:
    <<: *django
    image: home_automation_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: home_automation_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat


  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Panama
    volumes:
      - ./home_assistant/data:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
